version: '3.8'

services:
  django:
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_PRIVILEGED_TOKEN=${VAULT_PRIVILEGED_TOKEN}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_ENV=prod

  nginx:
    volumes:
      - ./nginx/nginx_prod.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - web-app-files:/var/www/SriLankanFoodWebsite
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
      - django

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - web-app-files:/var/www/SriLankanFoodWebsite
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
