# This contains overrides for the dev environment

version: '3.8'

services:

  nginx:
    volumes:
      - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - web-app-files:/var/www/SriLankanFoodWebsite
