# This contains overrides for the dev environment

version: '3.8'

services:

  django:
    build:
      context: .
      dockerfile: docker/Dockerfile.app.dev

  vault:
    build:
      context: .
      dockerfile: vault/Dockerfile.vault

  unseal_vault:
    build:
      context: .
      dockerfile: vault/Dockerfile.unseal

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx.dev
    volumes:
      - web-app-files:/var/www/SriLankanFoodWebsite
