# Generated by Django 5.1.1 on 2024-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
