# Generated by Django 5.1.1 on 2024-10-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contact_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_sent_date',
            field=models.DateTimeField(null=True),
        ),
    ]
