# Generated by Django 5.1.1 on 2024-10-17 01:55

from django.db import migrations, models


def insert_data(apps, schema_editor):
    system_preference_model = apps.get_model('main', 'SystemPreference')
    system_preference_model.objects.create(name='gstEnabled', type='boolean', value='False')
    system_preference_model.objects.create(name='gstRate', type='float', value='10.0')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_confirmation_sent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(insert_data)
    ]
