# Generated by Django 5.1 on 2024-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_first_name_alter_order_home_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_delivery_date',
            field=models.DateTimeField(null=True, verbose_name='Delivery Date'),
        ),
    ]
