# Generated by Django 5.1.1 on 2024-10-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_systempreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempreference',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
