# Generated by Django 5.1 on 2024-08-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_requested_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='instructions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='instructions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='chilli_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='contains_peanuts',
            field=models.BooleanField(default=False),
        ),
    ]
