# Generated by Django 5.1.1 on 2024-10-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
