# Generated by Django 5.1 on 2024-09-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cartitem_instructions_orderproduct_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('preferred_contact', models.CharField(choices=[('EMAIL', 'Email'), ('MOBILE', 'Mobile'), ('HOME_PHONE', 'Home Phone')], default='EMAIL', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('home_phone', models.CharField(max_length=20, null=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contacttype')),
            ],
        ),
    ]
