# Generated by Django 5.1 on 2024-09-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_contact_email_alter_contact_home_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='response_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Stars - Worst food ever!'), (1, '1 Star - I wish I had spent that money elsewhere'), (2, '2 Stars - Food was edible, but wont be coming back'), (3, '3 Stars - Was nice but nothing out of the ordinary'), (4, '4 Stars - Pretty, pretty, pretty good'), (5, '5 Stars - Oooh la la - Restaurant Quality')]),
        ),
    ]
