# Generated by Django 5.1.1 on 2024-10-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_productstock_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, unique=True)),
                ('from_email', models.EmailField(max_length=320)),
                ('cc_email', models.EmailField(max_length=320, null=True)),
                ('bcc_email', models.EmailField(max_length=320, null=True)),
            ],
        ),
    ]
