# Generated by Django 5.1.1 on 2024-10-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_emailconfiguration_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='bcc_email',
            field=models.EmailField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=320, null=True),
        ),
    ]
