# Generated by Django 5.1 on 2024-09-03 06:40

import main.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_contact_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[(main.enums.ContactNotificationTypeEnum['EMAIL'], 'Email'), (main.enums.ContactNotificationTypeEnum['MOBILE'], 'Mobile'), (main.enums.ContactNotificationTypeEnum['HOME_PHONE'], 'Home Phone')], default='EMAIL', max_length=20, null=True),
        ),
    ]
