# Generated by Django 5.1.1 on 2024-11-06 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_productstock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
