# Generated by Django 5.1 on 2024-09-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_contact_product_contact_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('MOBILE', 'Mobile'), ('HOME_PHONE', 'Home Phone')], default='EMAIL', max_length=20, null=True),
        ),
    ]
