# Generated by Django 5.1 on 2024-09-04 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_faqcategory_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='active',
        ),
    ]
