# Generated by Django 5.1 on 2024-09-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_available_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
