# Generated by Django 5.1 on 2024-09-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='main.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
