FROM nginx:latest

# Use this prior to certificates being setup  (sld-nginx-prod image)
# COPY ./nginx/nginx_prod.conf /etc/nginx/conf.d/default.conf

# Copy this after cert has been configured (sld-nginx-prod-postcert image)
COPY ./nginx/nginx_prod.conf.secure /etc/nginx/conf.d/default.conf
COPY ./nginx/proxy_params /etc/nginx/proxy_params
