name: Build and Push Docker Image to GHCP

on:
  push:
    branches:
      - master    # Trigger the workflow only when a PR is merged into "master"

env:
  SLD_APP_IMAGE: "ghcr.io/mrmansly/sld-app-prod:latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GHCR_TOKEN }}  # GitHub's token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag images
        run: |
          # Build the SLD Django app image explicitly (NOTE: nginx, vault, unseal_vault and certbot are not expected
          # to change and can be excluded from being built.
          docker build -f docker/Dockerfile.app.prod -t $SLD_APP_IMAGE .
          
          # Also tag build with SHA Commit# for better traceability
          TAG="${{ github.sha }}"
          docker tag $SLD_APP_IMAGE ghcr.io/mrmansly/sld-app-prod:$TAG

      - name: Push Docker image to GHCR
        run: |
          docker push $SLD_APP_IMAGE

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io
