name: Manual Trigger Workflows

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Choose the container to build and push to GHCR'
        required: true
        default: 'sri_lankan_delights_app'
        options:
          - nginx
          - nginx_postcert
          - vault
          - unseal_vault
          - sri_lankan_delights_app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and tag images
        run: |
          case ${{ github.events.input.image }} in
          
            # Pre SSL Certification Setup Nginx Image
            nginx) 
              IMAGE="ghcr.io/mrmansly/sld-nginx-prod:latest"
          
              docker build -f nginx/Dockerfile.nginx.prod -t $IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $IMAGE ghcr.io/mrmansly/sld-nginx-prod:$TAG
              ;;
          
            # Post SSL Certification Nginx Image
            nginx_postcert) 
              IMAGE="ghcr.io/mrmansly/sld-nginx-prod-postcert:latest"
          
              docker build -f nginx/Dockerfile.nginx.prod-postcert -t $IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $IMAGE ghcr.io/mrmansly/sld-nginx-prod-postcert:$TAG
              ;;
          
            # Vault Image
            vault)
              IMAGE="ghcr.io/mrmansly/sld-vault:latest"
          
              docker build -f vault/Dockerfile.vault -t $IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $IMAGE ghcr.io/mrmansly/sld-vault:$TAG
              ;;
          
            # Unseal Vault Image
            unseal_vault)
              IMAGE="ghcr.io/mrmansly/sld-unseal-vault:latest"
          
              docker build -f vault/Dockerfile.unseal -t $IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $IMAGE ghcr.io/mrmansly/sld-unseal-vault:$TAG
              ;;
          
            # Sri Lankan Delights Django App
            sri_lankan_delights_app)
              IMAGE="ghcr.io/mrmansly/sld-app-prod:latest"
          
              docker build -f docker/Dockerfile.app.prod -t $IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $IMAGE ghcr.io/mrmansly/sld-app-prod:$TAG
              ;;
          
            *)
              echo "Invalid image selection"
              exit 1
              ;;
          
          esac

      - name: Push Docker image to GHCR
        if: success()
        run: |
          case ${{ github.events.input.image }} in
            nginx)
              docker push ghcr.io/mrmansly/sld-nginx-prod:latest
              ;;
          
            nginx_postcert)
              docker push ghcr.io/mrmansly/sld-nginx-prod-postcert:latest
              ;;
          
            vault)
              docker push ghcr.io/mrmansly/sld-vault:latest
              ;;
          
            unseal_vault)
              docker push ghcr.io/mrmansly/sld-unseal-vault:latest
              ;;
          
            sri_lankan_delights_app)
              docker push ghcr.io/mrmansly/sld-app-prod:latest
              ;;
          
          esac
