name: Manual Trigger Workflows

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Choose the container to build and push to GHCR'
        required: true
        default: 'sri_lankan_delights_app'
        options:
          - nginx
          - nginx_postcert
          - vault
          - unseal_vault
          - sri_lankan_delights_app

env:
  SLD_APP_IMAGE: "ghcr.io/mrmansly/sld-app-prod:latest"
  NGINX_IMAGE: "ghcr.io/mrmansly/sld-nginx-prod:latest"
  NGINX_POSTCERT_IMAGE: "ghcr.io/mrmansly/sld-nginx-prod-postcert:latest"
  VAULT_IMAGE: "ghcr.io/mrmansly/sld-vault:latest"
  UNSEAL_VAULT_IMAGE: "ghcr.io/mrmansly/sld-unseal-vault:latest"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GHCR_TOKEN }}  # GitHub's token

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and tag images
        run: |
          case ${{ github.events.inputs.image }} in
          
            # Pre SSL Certification Setup Nginx Image
            nginx) 
              docker build -f nginx/Dockerfile.nginx.prod -t $NGINX_IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $NGINX_IMAGE ghcr.io/mrmansly/sld-nginx-prod:$TAG
              ;;
          
            # Post SSL Certification Nginx Image
            nginx_postcert) 
              docker build -f nginx/Dockerfile.nginx.prod-postcert -t $NGINX_POSTCERT_IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $NGINX_POSTCERT_IMAGE ghcr.io/mrmansly/sld-nginx-prod-postcert:$TAG
              ;;
          
            # Vault Image
            vault)
              docker build -f vault/Dockerfile.vault -t $VAULT_IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $VAULT_IMAGE ghcr.io/mrmansly/sld-vault:$TAG
              ;;
          
            # Unseal Vault Image
            unseal_vault)
              docker build -f vault/Dockerfile.unseal -t $UNSEAL_VAULT_IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $UNSEAL_VAULT_IMAGE ghcr.io/mrmansly/sld-unseal-vault:$TAG
              ;;
          
            # Sri Lankan Delights Django App
            sri_lankan_delights_app)
              docker build -f docker/Dockerfile.app.prod -t $SLD_APP_IMAGE .
          
              # Also tag build with SHA Commit# for better traceability
              TAG="${{ github.sha }}"
              docker tag $SLD_APP_IMAGE ghcr.io/mrmansly/sld-app-prod:$TAG
              ;;
          
            *)
              echo "Invalid image selection"
              exit 1
              ;;
          
          esac

      - name: Push Docker image to GHCR
        if: success()
        run: |
          case ${{ github.events.inputs.image }} in
            nginx)
              docker push $NGINX_IMAGE
              ;;
          
            nginx_postcert)
              docker push $NGINX_POSTCERT_IMAGE
              ;;
          
            vault)
              docker push $VAULT_IMAGE
              ;;
          
            unseal_vault)
              docker push $UNSEAL_VAULT_IMAGE
              ;;
          
            sri_lankan_delights_app)
              docker push $SLD_APP_IMAGE
              ;;
          
          esac

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io
